sonar.projectKey=Samrudhii2005_CI-CD-Pipeline-Automation
sonar.organization=samrudhii2005

sonar.sources=.
sonar.tests=tests

sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml